#%RAML 1.0
title: user-florence-proc

types:
  UsersDataType: !include datatype/usersDataType.raml

/users:
  get:
    queryParameters:    
      usersName: 
        type: string
        required: false  
      usersSurname:
        type: string        
        required: false    
    responses:
      200:
        body:
          application/json: 
            type: UsersDataType[]
            examples:
              output: !include examples/usersExampleArray.raml                
                
  post:
    body:
      multipart/form-data:
        properties:          
          fileContent:
            type: file
            fileTypes: ['application/csv','text/csv']
            required: true
               
    responses:
      201:
        body:
          application/json: 
            example:
              message: Users created!
              
            
  